background_opacity 1
background_blur 0
dynamic_background_opacity false

window_padding_width 20
single_window_padding_width 20
inactive_text_alpha 0.85

cursor_trail 3
cursor_trail_decay 0.08 0.5
cursor_trail_start_threshold 2
cursor_trail_color none
